import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Building2, CircleHelp, Database, Factory, FileCheck2, Search } from 'lucide-react';
import type { LoadPipelineDataset, PipelineClass, PipelineProject } from '../shared/market-types';
import { CAPACITY_LABELS as CAPACITIES, externalUrl, marketDate, marketFetch, marketNumber, qualifiedCapacity } from './MarketPanel';
import './market.css';

const CLASSES: Record<PipelineClass, string> = { application: '공식 접속 신청', utility_register: '사업자 공개 목록', contract: '공급·접속 계약', announced: '발표·계획', grid_support: '계통 보강 참고', historical: '과거 기록' };
const SECTORS: Record<PipelineProject['sector'], string> = { data_center: '데이터센터', manufacturing: '제조·대형 공장', crypto: '암호화폐 채굴', other: '기타 수용가', undisclosed: '업종 미공개' };
const STATUSES: Record<PipelineProject['status'], string> = { planned: '계획', active: '진행', construction: '공사', operating: '운영', withdrawn: '철회', unknown: '진행 상태 미공개' };

export default function LoadPipelinePanel({ revision, onRegister }: { revision: number; onRegister: () => void }) {
  const [data, setData] = useState<LoadPipelineDataset | null>(null);
  const [error, setError] = useState('');
  const [query, setQuery] = useState('');
  const [region, setRegion] = useState('');
  const [sector, setSector] = useState('');
  const [classification, setClassification] = useState('');
  const [reference, setReference] = useState(false);
  const [limit, setLimit] = useState(20);
  const [allAggregates, setAllAggregates] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); setError('');
    marketFetch<LoadPipelineDataset>('/api/load-pipeline', controller.signal).then(setData).catch(e => { if (e.name !== 'AbortError') setError(e.message); });
    return () => controller.abort();
  }, [revision]);
  useEffect(() => { setLimit(20); }, [query, region, sector, classification, reference]);
  useEffect(() => setAllAggregates(false), [region]);
  if (!data) return <div className={`market-loading ${error ? 'market-error' : ''}`} role={error ? 'alert' : 'status'}><Database size={22} />{error || '공개 수용가 자료를 불러오는 중…'}</div>;
  const regions = [...new Set([...data.projects.map(row => row.region), ...data.aggregates.map(row => row.region)])].sort();
  const selectedProjects = data.projects.filter(row => {
    if (region && row.region !== region || sector && row.sector !== sector || classification && row.classification !== classification) return false;
    if (!classification && !reference && ['grid_support', 'historical'].includes(row.classification)) return false;
    return !query.trim() || [row.name, row.region, row.state, row.evidence, row.sourceName].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  });
  const aggregates = data.aggregates.filter(row => !region || row.region === region);
  const official = data.projects.filter(row => row.classification === 'application').length;
  const broader = data.projects.filter(row => ['utility_register', 'contract', 'announced'].includes(row.classification)).length;
  const undisclosed = data.projects.filter(row => row.capacityMw === null).length;
  return <div className="pipeline-view">
    <section className="market-intro pipeline-intro"><div className="market-intro-icon"><Building2 size={25} /></div><div><span className="eyebrow">LARGE LOAD INTELLIGENCE</span><h2>공개 신청 원장 너머의 수용가 파이프라인</h2><p>데이터센터와 대형 공장의 신청·계약·발표 자료를 근거별로 살펴봅니다.</p></div></section>
    <div className="market-notice"><CircleHelp size={18} /><div><strong>처음 보인 53건은 미국 전체 수용가 사업 수가 아닙니다.</strong><p>53건은 NYISO 공개 원장의 활성 신청입니다. 다른 지역은 고객 정보를 공개하지 않거나 전력회사별 자료·계약·집계로 나누어 발표합니다. 아래 자료는 그 범위를 넓힌 공개 기록·사례 조사입니다. 운영·철회 기록도 구분해 보존하며, 전체 건수를 활성 접속 사업 수로 해석하지 않습니다. 발표나 계약만으로 접속 신청을 완료했다고 보지 않습니다.</p><button className="text-button" onClick={onRegister}>병목점수 집계용 신청 원장 보기 <ArrowRight size={14} /></button></div></div>
    {error && <div className="market-error" role="alert">최근 재조회 실패: {error} 이전에 불러온 자료를 표시합니다.</div>}
    <div className="pipeline-summary"><article><FileCheck2 size={20} /><span>공식 신청 기록으로 분류</span><strong>{marketNumber(official)}<small>건</small></strong><p>운영·철회 기록 포함 · 활성 수와 별도</p></article><article><Building2 size={20} /><span>공개 목록·계약·발표</span><strong>{marketNumber(broader)}<small>건</small></strong><p>신청 완료 여부는 별도 확인</p></article><article><Database size={20} /><span>공식 지역·사업자 집계</span><strong>{marketNumber(data.aggregates.length)}<small>개</small></strong><p>개별 프로젝트와 합산하지 않음</p></article><article><CircleHelp size={20} /><span>개별 용량 미공개</span><strong>{marketNumber(undisclosed)}<small>건</small></strong><p>0 MW로 간주하지 않음</p></article></div>
    <section className="panel pipeline-aggregates"><div className="panel-heading"><div><span className="eyebrow">PUBLISHED AGGREGATE CONTEXT</span><h2>개별 명단이 없어도, 공개된 규모는 확인</h2></div><span className="market-badge">집계 자료 · 개별 신청과 별도</span></div><p className="market-section-description">집계 범위·기준일이 서로 다르며 일부 중복됩니다. 지역별 숫자를 더해 미국 전체 신청 용량으로 만들지 않습니다.</p><div className="pipeline-aggregate-grid">{aggregates.length ? aggregates.slice(0, allAggregates ? aggregates.length : 3).map(row => <article className="pipeline-aggregate" key={row.id}><div className="pipeline-card-top"><span>{row.region}</span><a href={externalUrl(row.sourceUrl)} target="_blank" rel="noreferrer" aria-label={`${row.name} 원문 열기`}><ArrowUpRight size={16} /></a></div><h3>{row.name}</h3><strong className="aggregate-value">{qualifiedCapacity(row)}{row.capacityMw !== null && <small> MW</small>}</strong><span className="aggregate-basis">{CAPACITIES[row.capacityBasis]}{row.projectCount !== null ? ` · ${marketNumber(row.projectCount)}건` : ' · 건수 미공개'}</span><p>{row.scope}</p>{row.caveats.length > 0 && <ul>{row.caveats.map(caveat => <li key={caveat}>{caveat}</li>)}</ul>}<div className="pipeline-provenance"><a href={externalUrl(row.sourceUrl)} target="_blank" rel="noreferrer">{row.sourceName} <ArrowUpRight size={11} /></a><span>원자료 {marketDate(row.sourceAsOf, false)}</span><span>확인 {marketDate(row.checkedAt)}{row.checkedAt?.includes('T') ? ' KST' : ''}</span></div></article>) : <p className="market-empty">선택 권역의 집계 자료를 확보하지 못했습니다.</p>}</div>{aggregates.length > 3 && <div className="pipeline-more"><span>{marketNumber(aggregates.length)}개 집계 · 중복 범위 포함</span><button className="button" onClick={() => setAllAggregates(value => !value)}>{allAggregates ? "간단히 보기" : "집계 자료 모두 보기"}</button></div>}</section>
    <section className="panel pipeline-projects"><div className="panel-heading"><div><span className="eyebrow">PROJECT EVIDENCE REGISTER</span><h2>수용가 사업과 공개 신청 기록</h2></div><span className="market-timezone">{marketNumber(selectedProjects.length)}개 기록·사례</span></div><div className="pipeline-filters"><label className="pipeline-search"><Search size={16} /><input aria-label="수용가 사업 검색" value={query} onChange={e => setQuery(e.target.value)} placeholder="사업명, 회사, 지역, 근거 검색" /></label><label><span className="sr-only">수용가 권역</span><select aria-label="수용가 권역" value={region} onChange={e => setRegion(e.target.value)}><option value="">모든 권역</option>{regions.map(value => <option key={value}>{value}</option>)}</select></label><label><span className="sr-only">수용가 업종</span><select aria-label="수용가 업종" value={sector} onChange={e => setSector(e.target.value)}><option value="">모든 업종</option>{Object.entries(SECTORS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="sr-only">수용가 근거 구분</span><select aria-label="수용가 근거 구분" value={classification} onChange={e => setClassification(e.target.value)}><option value="">모든 근거 구분</option>{Object.entries(CLASSES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="pipeline-reference"><input type="checkbox" checked={reference} onChange={e => setReference(e.target.checked)} disabled={!!classification} />과거·계통 보강 참고 포함</label></div><p className="pipeline-capacity-note">MW 옆의 용량 기준을 확인하세요. IT 설비 전력, 부지 전체 전력, 계통 요청 전력은 서로 같지 않으며 합계 용량을 제공하지 않습니다. 동일 사업의 여러 근거가 겹칠 수 있습니다.</p><div className="pipeline-project-list">{selectedProjects.slice(0, limit).map(row => <ProjectEvidence key={row.id} project={row} />)}{!selectedProjects.length && <div className="market-empty"><Factory size={24} /><p>선택 조건에 해당하는 공개 근거가 없습니다.</p><small>해당 업종의 사업이 없다는 뜻은 아닙니다.</small><button className="text-button" onClick={() => { setQuery(''); setRegion(''); setSector(''); setClassification(''); }}>검색 조건 초기화</button></div>}</div>{selectedProjects.length > limit && <div className="pipeline-more"><span>{marketNumber(limit)} / {marketNumber(selectedProjects.length)}건</span><button className="button" onClick={() => setLimit(value => value + 20)}>20건 더 보기</button></div>}</section>
    <section className="pipeline-limitations"><h2>아직 확인하지 못한 범위</h2><ul>{data.limitations.map(item => <li key={item}>{item}</li>)}</ul><p>자료 생성 {marketDate(data.generatedAt)} KST · 개별 원자료 기준일과 실제 확인 시각은 각 카드에 표시합니다.</p></section>
  </div>;
}

function ProjectEvidence({ project: row }: { project: PipelineProject }) {
  return <article className="pipeline-project"><div className="pipeline-project-icon">{row.sector === 'manufacturing' ? <Factory size={20} /> : <Building2 size={20} />}</div><div className="pipeline-project-main"><div className="pipeline-project-labels"><span className={`market-badge class-${row.classification}`}>{CLASSES[row.classification]}</span><span>{row.region}{row.state ? ` · ${row.state}` : ''}</span><span>{SECTORS[row.sector]}</span><span className="pipeline-record-status">{STATUSES[row.status]}</span></div><h3>{row.name}</h3><p>{row.evidence}</p><details><summary>근거·공개 범위 확인</summary><div className="pipeline-evidence-detail"><dl><div><dt>문서상 진행 상태</dt><dd>{STATUSES[row.status]}</dd></div><div><dt>원자료 기준일</dt><dd>{marketDate(row.sourceAsOf, false)}</dd></div><div><dt>실제 확인 시각</dt><dd>{marketDate(row.checkedAt)}{row.checkedAt?.includes('T') ? ' KST' : ''}</dd></div>{row.linkedProjectId && <div><dt>연결한 신청 ID</dt><dd>{row.linkedProjectId}</dd></div>}</dl>{row.caveats.length > 0 && <ul>{row.caveats.map(caveat => <li key={caveat}>{caveat}</li>)}</ul>}<a href={externalUrl(row.sourceUrl)} target="_blank" rel="noreferrer">{row.sourceName} 원문 <ArrowUpRight size={13} /></a></div></details></div><div className="pipeline-project-capacity"><strong>{marketNumber(row.capacityMw)}{row.capacityMw !== null && <small>MW</small>}</strong><span>{CAPACITIES[row.capacityBasis]}</span><a href={externalUrl(row.sourceUrl)} target="_blank" rel="noreferrer">출처 <ArrowUpRight size={13} /></a></div></article>;
}
